version: '3.8'
services:
  postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=my_health
  server:
    build: ./server
    command: gunicorn --workers=4 --bind 0.0.0.0:8000 server.wsgi:application
    volumes:
      - ./server/:/usr/src/server/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./server/.env.prod

volumes:
  postgres_data: