version: '3.8'
services:
  postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=my_health
  backend:
    build: ./server
    command: gunicorn --workers=4 --bind 0.0.0.0:8000 server.wsgi:application
    volumes:
      - static_data:/usr/src/server/static
      - media_data:/usr/src/server/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./server/.env.prod
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - static_data:/usr/src/server/static/
      - media_data:/usr/src/server/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  media_data:
  static_data: