version: '3.3'
services:
  postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=my_health
  backend:
    build: ./server
    command: gunicorn -e env_file=.env.prod --workers=4 --bind 0.0.0.0:8000 server.wsgi:application
    volumes:
      - static_data:/usr/src/server/static
      - media_data:/usr/src/server/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - static_data:/usr/src/server/static/
      - media_data:/usr/src/server/media/
      - ./certbot/www:/var/www/certbot/:ro
    depends_on:
      - backend
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw

volumes:
  postgres_data:
  media_data:
  static_data: